<?php

namespace Database\Seeders;

use App\Models\Entity;
use App\Models\VehicleLease;
use Illuminate\Database\Seeder;

class VehicleLeasesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get a dealer entity
        $entity = Entity::where('type', 'dealer')->first();

        if (!$entity) {
            $this->command->warn('No dealer entity found. Creating lease vehicles without entity.');
        }

        // Sample lease vehicles data
        $leaseVehicles = [
            [
                'vehicle_title' => '2024 Toyota Camry LE',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Toyota',
                'vehicle_model' => 'Camry',
                'vehicle_variant' => 'LE',
                'body_type' => 'Sedan',
                'fuel_type' => 'Petrol',
                'transmission' => 'Automatic',
                'engine_capacity' => '2.5L',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Pearl White',
                'seats' => 5,
                'features' => ['Air Conditioning', 'Power Steering', 'Bluetooth', 'USB Ports', 'Cruise Control', 'Backup Camera', 'Keyless Entry'],
                'vehicle_description' => 'Brand new 2024 Toyota Camry LE with all modern features. Perfect for daily commuting with excellent fuel economy and reliability.',
                'monthly_payment' => 450.00,
                'lease_term_months' => 36,
                'down_payment' => 2000.00,
                'is_featured' => true,
            ],
            [
                'vehicle_title' => '2024 Honda CR-V EX',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Honda',
                'vehicle_model' => 'CR-V',
                'vehicle_variant' => 'EX',
                'body_type' => 'SUV',
                'fuel_type' => 'Petrol',
                'transmission' => 'Automatic',
                'engine_capacity' => '1.5L Turbo',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Rallye Red',
                'seats' => 5,
                'features' => ['All-Wheel Drive', 'Touchscreen Display', 'Honda Sensing', 'Apple CarPlay', 'Android Auto', 'Moonroof', 'Power Tailgate'],
                'vehicle_description' => 'Spacious and versatile 2024 Honda CR-V EX. Ideal for families with advanced safety features and plenty of cargo space.',
                'monthly_payment' => 520.00,
                'lease_term_months' => 36,
                'down_payment' => 2500.00,
                'is_featured' => true,
            ],
            [
                'vehicle_title' => '2024 Nissan Altima SV',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Nissan',
                'vehicle_model' => 'Altima',
                'vehicle_variant' => 'SV',
                'body_type' => 'Sedan',
                'fuel_type' => 'Petrol',
                'transmission' => 'CVT',
                'engine_capacity' => '2.5L',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Super Black',
                'seats' => 5,
                'features' => ['Nissan Safety Shield 360', 'ProPILOT Assist', 'Bose Audio', 'Heated Seats', 'Remote Start', 'NissanConnect'],
                'vehicle_description' => 'Sporty and efficient 2024 Nissan Altima SV with advanced driver assistance technology and premium amenities.',
                'monthly_payment' => 480.00,
                'lease_term_months' => 36,
                'down_payment' => 2200.00,
                'is_featured' => true,
            ],
            [
                'vehicle_title' => '2024 Ford F-150 XLT',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Ford',
                'vehicle_model' => 'F-150',
                'vehicle_variant' => 'XLT',
                'body_type' => 'Truck',
                'fuel_type' => 'Petrol',
                'transmission' => 'Automatic',
                'engine_capacity' => '3.5L EcoBoost',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Oxford White',
                'seats' => 5,
                'features' => ['Ford Co-Pilot360', 'SYNC 4', 'Trailer Tow Package', 'FX4 Off-Road Package', 'Power Sliding Rear Window', 'Bed Liner'],
                'vehicle_description' => 'Powerful and capable 2024 Ford F-150 XLT. Perfect for work or adventure with impressive towing capacity.',
                'monthly_payment' => 680.00,
                'lease_term_months' => 48,
                'down_payment' => 3500.00,
                'is_featured' => false,
            ],
            [
                'vehicle_title' => '2024 Hyundai Elantra SEL',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Hyundai',
                'vehicle_model' => 'Elantra',
                'vehicle_variant' => 'SEL',
                'body_type' => 'Sedan',
                'fuel_type' => 'Petrol',
                'transmission' => 'Automatic',
                'engine_capacity' => '2.0L',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Fluid Metal',
                'seats' => 5,
                'features' => ['Hyundai SmartSense', 'Wireless Apple CarPlay', 'Wireless Android Auto', 'Bluelink', 'Smart Cruise Control', 'Lane Following Assist'],
                'vehicle_description' => 'Modern and tech-forward 2024 Hyundai Elantra SEL with comprehensive warranty and advanced safety features.',
                'monthly_payment' => 380.00,
                'lease_term_months' => 36,
                'down_payment' => 1800.00,
                'is_featured' => false,
            ],
            [
                'vehicle_title' => '2024 Chevrolet Equinox LT',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Chevrolet',
                'vehicle_model' => 'Equinox',
                'vehicle_variant' => 'LT',
                'body_type' => 'SUV',
                'fuel_type' => 'Petrol',
                'transmission' => 'Automatic',
                'engine_capacity' => '1.5L Turbo',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Summit White',
                'seats' => 5,
                'features' => ['Chevrolet Infotainment 3', 'Apple CarPlay', 'Android Auto', 'Wi-Fi Hotspot', 'Chevy Safety Assist', 'Active Safety Package'],
                'vehicle_description' => 'Comfortable and efficient 2024 Chevrolet Equinox LT with modern technology and impressive fuel economy.',
                'monthly_payment' => 490.00,
                'lease_term_months' => 36,
                'down_payment' => 2300.00,
                'is_featured' => false,
            ],
            [
                'vehicle_title' => '2024 Mazda CX-5 Touring',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Mazda',
                'vehicle_model' => 'CX-5',
                'vehicle_variant' => 'Touring',
                'body_type' => 'SUV',
                'fuel_type' => 'Petrol',
                'transmission' => 'Automatic',
                'engine_capacity' => '2.5L',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Machine Gray Metallic',
                'seats' => 5,
                'features' => ['i-Activsense Safety Technology', 'Mazda Connect', 'Bose Audio', 'Power Liftgate', 'Mazda Radar Cruise Control', 'Blind Spot Monitoring'],
                'vehicle_description' => 'Stylish and refined 2024 Mazda CX-5 Touring with premium interior and engaging driving dynamics.',
                'monthly_payment' => 510.00,
                'lease_term_months' => 36,
                'down_payment' => 2400.00,
                'is_featured' => false,
            ],
            [
                'vehicle_title' => '2024 Subaru Outback Premium',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Subaru',
                'vehicle_model' => 'Outback',
                'vehicle_variant' => 'Premium',
                'body_type' => 'Wagon',
                'fuel_type' => 'Petrol',
                'transmission' => 'CVT',
                'engine_capacity' => '2.5L',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Ice Silver Metallic',
                'seats' => 5,
                'features' => ['Subaru EyeSight', 'All-Wheel Drive', 'SUBARU STARLINK', 'X-Mode', 'Roof Rails', 'All-Weather Package'],
                'vehicle_description' => 'Adventure-ready 2024 Subaru Outback Premium with standard all-wheel drive and excellent ground clearance.',
                'monthly_payment' => 530.00,
                'lease_term_months' => 36,
                'down_payment' => 2600.00,
                'is_featured' => false,
            ],
            [
                'vehicle_title' => '2024 Volkswagen Jetta SE',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Volkswagen',
                'vehicle_model' => 'Jetta',
                'vehicle_variant' => 'SE',
                'body_type' => 'Sedan',
                'fuel_type' => 'Petrol',
                'transmission' => 'Automatic',
                'engine_capacity' => '1.5L Turbo',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Platinum Gray Metallic',
                'seats' => 5,
                'features' => ['IQ.DRIVE', 'Digital Cockpit', 'App-Connect', 'Wireless Charging', 'BeatsAudio', 'Keyless Access'],
                'vehicle_description' => 'European-inspired 2024 Volkswagen Jetta SE with premium build quality and advanced technology.',
                'monthly_payment' => 420.00,
                'lease_term_months' => 36,
                'down_payment' => 2000.00,
                'is_featured' => false,
            ],
            [
                'vehicle_title' => '2024 Kia Sorento SX',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Kia',
                'vehicle_model' => 'Sorento',
                'vehicle_variant' => 'SX',
                'body_type' => 'SUV',
                'fuel_type' => 'Petrol',
                'transmission' => 'Automatic',
                'engine_capacity' => '2.5L Turbo',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Gravity Gray',
                'seats' => 7,
                'features' => ['Kia Drive Wise', '10.25-inch Touchscreen', 'Harman Kardon Audio', 'Third-Row Seating', 'Power Liftgate', 'Surround View Monitor'],
                'vehicle_description' => 'Spacious three-row 2024 Kia Sorento SX perfect for large families with premium features and excellent warranty.',
                'monthly_payment' => 590.00,
                'lease_term_months' => 48,
                'down_payment' => 3000.00,
                'is_featured' => false,
            ],
            [
                'vehicle_title' => '2024 BMW 3 Series 330i',
                'vehicle_year' => 2024,
                'vehicle_make' => 'BMW',
                'vehicle_model' => '3 Series',
                'vehicle_variant' => '330i',
                'body_type' => 'Sedan',
                'fuel_type' => 'Petrol',
                'transmission' => 'Automatic',
                'engine_capacity' => '2.0L Turbo',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Alpine White',
                'seats' => 5,
                'features' => ['BMW Live Cockpit', 'BMW Active Driving Assistant', 'Harman Kardon Sound', 'Sport Package', 'Heated Seats', 'Panoramic Sunroof'],
                'vehicle_description' => 'Luxury performance sedan 2024 BMW 3 Series 330i with exceptional handling and premium interior.',
                'monthly_payment' => 750.00,
                'lease_term_months' => 36,
                'down_payment' => 4000.00,
                'is_featured' => false,
            ],
            [
                'vehicle_title' => '2024 Mercedes-Benz C-Class C300',
                'vehicle_year' => 2024,
                'vehicle_make' => 'Mercedes-Benz',
                'vehicle_model' => 'C-Class',
                'vehicle_variant' => 'C300',
                'body_type' => 'Sedan',
                'fuel_type' => 'Petrol',
                'transmission' => 'Automatic',
                'engine_capacity' => '2.0L Turbo',
                'mileage' => 0,
                'condition' => 'new',
                'color_exterior' => 'Obsidian Black Metallic',
                'seats' => 5,
                'features' => ['MBUX Infotainment', 'Mercedes-Benz User Experience', 'Burmester Audio', 'AMG Line Package', 'Digital Instrument Cluster', 'Ambient Lighting'],
                'vehicle_description' => 'Luxurious 2024 Mercedes-Benz C-Class C300 with cutting-edge technology and sophisticated design.',
                'monthly_payment' => 780.00,
                'lease_term_months' => 36,
                'down_payment' => 4500.00,
                'is_featured' => false,
            ],
        ];

        foreach ($leaseVehicles as $index => $vehicleData) {
            $isFeatured = $vehicleData['is_featured'] ?? ($index < 3);
            $leaseTerm = $vehicleData['lease_term_months'];
            $monthlyPayment = $vehicleData['monthly_payment'];
            $downPayment = $vehicleData['down_payment'];
            $securityDeposit = $monthlyPayment * 1; // 1 month security
            $totalPrice = ($monthlyPayment * $leaseTerm) + $downPayment;
            
            VehicleLease::create([
                'entity_id' => $entity?->id,
                // Vehicle Information
                'vehicle_title' => $vehicleData['vehicle_title'],
                'vehicle_year' => $vehicleData['vehicle_year'],
                'vehicle_make' => $vehicleData['vehicle_make'],
                'vehicle_model' => $vehicleData['vehicle_model'],
                'vehicle_variant' => $vehicleData['vehicle_variant'],
                'body_type' => $vehicleData['body_type'],
                'fuel_type' => $vehicleData['fuel_type'],
                'transmission' => $vehicleData['transmission'],
                'engine_capacity' => $vehicleData['engine_capacity'],
                'mileage' => $vehicleData['mileage'],
                'condition' => $vehicleData['condition'],
                'color_exterior' => $vehicleData['color_exterior'],
                'seats' => $vehicleData['seats'],
                'features' => $vehicleData['features'],
                'vehicle_description' => $vehicleData['vehicle_description'],
                // Lease Information
                'lease_title' => $leaseTerm . '-Month ' . ($isFeatured ? 'Premium' : 'Standard') . ' Lease',
                'lease_description' => 'Affordable leasing option for the ' . $vehicleData['vehicle_title'] . '. ' . 
                    ($isFeatured ? 'Featured lease with special benefits and priority service.' : 'Great value lease with flexible terms.') . 
                    ' This is a brand new vehicle with full manufacturer warranty.',
                'monthly_payment' => $monthlyPayment,
                'lease_term_months' => $leaseTerm,
                'down_payment' => $downPayment,
                'security_deposit' => $securityDeposit,
                'mileage_limit_per_year' => 15000,
                'excess_mileage_charge' => 0.25,
                'acquisition_fee' => 500,
                'disposition_fee' => 350,
                'maintenance_included' => $isFeatured,
                'insurance_included' => false,
                'min_credit_score' => $isFeatured ? 700 : 650,
                'min_monthly_income' => $monthlyPayment * 3,
                'min_age' => 21,
                'additional_requirements' => 'Valid driver\'s license and proof of income required. Insurance coverage must be maintained throughout lease term.',
                'purchase_option_available' => true,
                'residual_value' => round($totalPrice * 0.55, 2), // 55% residual value
                'early_termination_fee' => $monthlyPayment * 3,
                'status' => 'active',
                'is_featured' => $isFeatured,
                'priority' => $isFeatured ? (100 - ($index * 10)) : 0,
                'available_from' => now(),
                'available_until' => now()->addMonths(6),
                'included_services' => $isFeatured ? [
                    'Roadside Assistance',
                    '24/7 Customer Support',
                    'Free Oil Changes',
                    'Tire Rotation',
                    'Vehicle Health Checks',
                ] : [
                    'Roadside Assistance',
                    'Customer Support',
                    'Vehicle Health Checks',
                ],
                'notes' => 'Sample lease created by seeder - ' . now()->format('Y-m-d'),
            ]);
        }

        $this->command->info('Created ' . count($leaseVehicles) . ' vehicle leases successfully!');
    }
}
